### PR TITLE
Add support for proxy and random-agent

### PR DESCRIPTION
**Pull request by bp0lr**
Hi!
thank you for taking the time to review this pr.

This pr add support to use a proxy and a random agent for each query.

I hope you like it!.

imagen

imagen

### CODE REVIEW

**Comment by lc** [comment]
Hi @bp0lr, 

Thanks for this PR, I will try to review this as soon as I can!

**Comment by bp0lr** [comment]
sorry I thought common.go was for common functions.
I have moved random-useragent to main.go

thanks!

**Comment by bp0lr** [comment]
everything working and tested.

💯

**Comment by lc** [comment]
Looks good to me! Thank you

**Pull request merged**
